### PR TITLE
Fix several layout issues

### LINKED ISSUE #16: appointment-cs-slot-search adjustments for demo
- [x] Change Main-Color everything is based on to ~#f44336~ #8f071b (materialize class red)
- [x] Change Many-Calls-scheduled  cell bg to ~#f44336~ #8f071b (materialize class red)
- [x] Align Select button on right side of wrapper 
- [x] Color Select button in "light-green darken-2"
- [x] Change text on "Select" button to "Select Slot"

### PR DESCRIPTION
**Pull request by lucasmetzenbd**
- Read color base value from environment variable to make it easier to change.
- Change layout of Select button

This closes #16

### CODE REVIEW

File: app/helpers/color_helper.rb [hunk 1]
```diff
@@ -1,17 +1,17 @@
 require 'chroma'
 
 module ColorHelper
-  BLUE = [230, 100, 30].freeze
+  BASE_COLOR_HSV = (ENV['BASE_COLOR_HSV']).split(',').map(&:to_i).freeze
```
Comment (crobert-betterdoc) [inline app/helpers/color_helper.rb]: I'm missing a test that checks if the color values are correctly read from the environment. Also, what happens if for some reason the environment variable is invalid? How do we notice that?

Comment (lucasmetzenbd) [reply app/helpers/color_helper.rb]: Please see the now existing testcases in https://github.com/betterdoc-org/appointment-cs-free-slot-search/pull/18/commits/71d6957d9f1dc203a2a51ef76652794b92d75aad.

File: app/helpers/color_helper.rb [hunk 2]
```diff
@@ -1,17 +1,22 @@
 require 'chroma'
 
 module ColorHelper
-  BASE_COLOR_HSV = (ENV['BASE_COLOR_HSV']).split(',').map(&:to_i).freeze
-
   def compute_color_shades(intervals)
-    interval_value = (100 - BASE_COLOR_HSV[2]) / (intervals - 1).to_f
-    @shades = Array.new(intervals) { |i| (BASE_COLOR_HSV[2] + i * interval_value).ceil }
+    raise 'ENV["BASE_COLOR_HSL"] is empty' if ENV['BASE_COLOR_HSL'].nil?
```
Comment (crobert-betterdoc) [inline app/helpers/color_helper.rb]: Should be `.blank?` instead of `.nil?` which also catches empty values and not not non-existent values.

File: app/helpers/color_helper.rb [hunk 3]
```diff
@@ -1,17 +1,22 @@
...
+
+    begin
+      @base_color_hsl = ENV['BASE_COLOR_HSL'].split(',').map(&:to_i).freeze
+    rescue TypeError
```
Comment (crobert-betterdoc) [inline app/helpers/color_helper.rb]: Will an invalid value always return a type error?

File: app/helpers/color_helper.rb [hunk 4]
```diff
@@ -1,17 +1,22 @@
...
+      raise 'invalid HSL color value for ENV["BASE_COLOR_HSL"]'
+    end
+    interval_value = (100 - @base_color_hsl[2]) / (intervals - 1).to_f
```
Comment (crobert-betterdoc) [inline app/helpers/color_helper.rb]: What happens if the `base_color_hsl` array has less than two elements?

Comment (lucasmetzenbd) [reply app/helpers/color_helper.rb]: That would be a `TypeError` error.

File: app/helpers/color_helper.rb (hunk 3 above)
Comment (lucasmetzenbd) [reply app/helpers/color_helper.rb]: In the first try I thought it did but it seems I had an error in reasoning there since on further testing it didn't (anymore).
I've found a way to test multiple types of invalid value including incorrect numbers of array elements: https://github.com/betterdoc-org/appointment-cs-free-slot-search/blob/e05060a3aae1bb9eb06c4119c063c6062b72cc70/app/helpers/color_helper.rb#L9)
